# Generated by Django 5.0.7 on 2024-07-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('faculty_incharge', models.CharField(max_length=100)),
                ('faculty_id', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=100)),
                ('nip_status', models.CharField(max_length=100)),
            ],
        ),
    ]
