# Generated by Django 5.0.7 on 2024-07-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('lab_count', models.IntegerField()),
                ('year_1', models.IntegerField(default=0)),
                ('year_2', models.IntegerField(default=0)),
                ('year_3', models.IntegerField(default=0)),
                ('year_4', models.IntegerField(default=0)),
            ],
        ),
    ]
