# Generated by Django 5.0.7 on 2024-07-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0002_picmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('student_count', models.IntegerField()),
                ('lab_code', models.CharField(max_length=50)),
                ('faculty_incharges', models.CharField(max_length=100)),
                ('faculty_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
            ],
        ),
    ]
