# Generated by Django 5.0.7 on 2024-07-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0003_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='student_count',
        ),
        migrations.CreateModel(
            name='OnDutyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('lab_name', models.CharField(max_length=100)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_details_app.student')),
            ],
        ),
    ]
