# Generated by Django 5.0.7 on 2024-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0004_remove_faculty_student_count_ondutyapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ondutyapplication',
            name='applied_on',
        ),
        migrations.AddField(
            model_name='ondutyapplication',
            name='applied_dates',
            field=models.JSONField(default=list),
        ),
    ]
