# Generated by Django 5.0.7 on 2024-07-28 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0005_remove_ondutyapplication_applied_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ondutyapplication',
            name='applied_dates',
        ),
        migrations.AddField(
            model_name='ondutyapplication',
            name='applied_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
