# Generated by Django 5.0.7 on 2024-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0006_remove_ondutyapplication_applied_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='fi',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
