# Generated by Django 5.0.7 on 2024-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0007_faculty_fi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fi',
            field=models.CharField(max_length=100),
        ),
    ]
