# Generated by Django 5.0.7 on 2024-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0008_alter_faculty_fi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondutyapplication',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
