# Generated by Django 5.0.7 on 2024-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details_app', '0010_alter_ondutyapplication_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondutyapplication',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
